version: "3"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: ../Dockerfile
    container_name: gateway
    restart: on-failure
    networks:
      - ds
    volumes:
      - ./gateway/configs/local.yaml:/configs/config.yaml
    ports:
      - "8080:8080"

  cars-postgres:
    image: library/postgres:13
    container_name: cars-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    networks:
      - ds
    ports:
      - "5440:5432"

  cars-service:
    build:
      context: ./cars-service
      dockerfile: ../Dockerfile
    container_name: cars-service
    restart: on-failure
    networks:
      - ds
    volumes:
      - ./cars-service/configs/local.yaml:/configs/config.yaml
    ports:
      - "8070:8070"

  rental-postgres:
    image: library/postgres:13
    container_name: rental-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    networks:
      - ds
    ports:
      - "5442:5432"

  rental-service:
    build:
      context: ./rental-service
      dockerfile: ../Dockerfile
    container_name: rental-service
    restart: on-failure
    networks:
      - ds
    volumes:
      - ./rental-service/configs/local.yaml:/configs/config.yaml
    ports:
      - "8060:8060"

  payment-postgres:
    image: library/postgres:13
    container_name: payment-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    networks:
      - ds
    ports:
      - "5441:5432"

  payment-service:
    build:
      context: ./payment-service
      dockerfile: ../Dockerfile
    container_name: payment-service
    restart: on-failure
    networks:
      - ds
    volumes:
      - ./payment-service/configs/local.yaml:/configs/config.yaml
    ports:
      - "8050:8050"

# TODO добавить сервисы

networks:
  ds:
    driver: bridge
