{{- define "lib-chart.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    Postgres:
      Host: {{ .Values.config.postgres.host }}
      Port: {{ .Values.config.postgres.port }}
      User: {{ .Values.config.postgres.user }}
      Password: {{ .Values.config.postgres.password }}
      DBName: {{ .Values.config.postgres.db }}
    Port: {{ .Values.config.port }}
    LogLevel: {{ .Values.config.logLevel }}
    Services:
      Cars: {{ .Values.cars-service }}
      Rental: {{ .Values.rental-service }}
      Payment: {{ .Values.payment-service }}
{{- end -}}
