name: Build service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build:
    name: Build Cars-Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"

      - name: Go to workdir
        run: cd ${{ inputs.service-name }}

      - name: Tidy
        run: go mod tidy

      - name: Build service
        run: go build ./cmd/app/main.go
