name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-cars-service:
    name: Build cars-service
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: cars-service

  build-payment-service:
    name: Build payment-service
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: payment-service

  build-rental-service:
    name: Build rental-service
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: rental-service

  build-gateway-service:
    name: Build gateway
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: gateway

  autograding:
    name: Autograding
    needs:
      [
        "build-cars-service",
        "build-payment-service",
        "build-rental-service",
        "build-gateway-service",
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v

  build-image-cars-service:
    name: Build and push cars-service Docker image
    needs: ["build-cars-service", "autograding"]
    uses: ./.github/workflows/build-image.yml
    with:
      service-name: cars-service
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-image-payment-service:
    name: Build and push payment-service Docker image
    needs: ["build-payment-service", "autograding"]
    uses: ./.github/workflows/build-image.yml
    with:
      service-name: payment-service
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-image-rental-service:
    name: Build and push rental-service Docker image
    needs: ["build-rental-service", "autograding"]
    uses: ./.github/workflows/build-image.yml
    with:
      service-name: rental-service
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-image-gateway-service:
    name: Build and push gateway Docker image
    needs: ["build-gateway-service", "autograding"]
    uses: ./.github/workflows/build-image.yml
    with:
      service-name: gateway
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
